name: pysql
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - sqlalchemy
  - requests
  - pip
  - pip:
      - hydra-core
